-- SAAMS Official Nursery List — 36 active nurseries
-- Safe optional seed for a fresh database. Existing rows are updated by migration 07.
insert into public.nurseries (name_ar,name_en,active) values
('الرحمانية الجديدة','New Al Rahmaniya',true),
('مركز اللؤلؤية للطفولة المبكرة','Al Luluyah Early Childhood Center',true),
('مركز السيوح للطفولة المبكرة','Al Suyoh Early Childhood Center',true),
('واسط 2','Wasit 2',true),
('مركز الرحمانية للطفولة المبكرة','Al Rahmaniya Early Childhood Center',true),
('البديع','Al Badie',true),
('اللية','Al Liyah',true),
('القليعة','Al Qulaya',true),
('مركز البستان للطفولة المبكرة','Al Bustan Early Childhood Center',true),
('مركز كلباء للطفولة المبكرة','Kalba Early Childhood Center',true),
('الغيل','Al Ghail',true),
('الطيبة','Al Taybah',true),
('الحرس الأميري','Amiri Guard',true),
('الحمرية','Al Hamriyah',true),
('المدينة الباسمة','Al Madina Al Basima',true),
('الشرطي الصغير','Little Policeman',true),
('الثميد','Al Thameed',true),
('سهيلة','Suhaila',true),
('سهيلة الجديدة','New Suhaila',true),
('البرير','Al Barir',true),
('مليحة','Mleiha',true),
('القادسية','Al Qadisiyah',true),
('دبا الحصن','Dibba Al Hisn',true),
('السياقة','Driving',true),
('الشارقة النموذجية','Sharjah Model',true),
('مغيدر','Mughaidir',true),
('الشيماء','Al Shaimaa',true),
('المستقبل','Al Mustaqbal',true),
('غرفتي الصغيرة','My Little Room',true),
('جميلة','Jameela',true),
('الباحثة','Al Bahitha',true),
('النحوة','Al Nahwa',true),
('جامعة خورفكان','University of Khorfakkan',true),
('جامعة كلباء','University of Kalba',true),
('وادي الحلو','Wadi Al Helo',true),
('شيص','Shees',true)
on conflict (name_ar) do update set name_en=excluded.name_en, active=true;
